service: remote-compas
frameworkVersion: '3'

#useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stackTags:
    Owner: 'Francesco Strazzullo'
    Destroy: 'false'
  region: eu-south-1
  httpApi:
    cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline

package:
  patterns:
    - node_modules/**
    - .serverless/**

functions:
  app:
    handler: src/handlers/app.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY